biome-types:
  very-bad-fertile:
    biomes: [COLD_OCEAN, DEEP_COLD_OCEAN, DESERT, DEEP_DARK, DEEP_FROZEN_OCEAN,
             FROZEN_PEAKS, FROZEN_OCEAN, FROZEN_RIVER, DRIPSTONE_CAVES, ICE_SPIKES,
             JAGGED_PEAKS, BASALT_DELTAS, CRIMSON_FOREST, END_BARRENS, END_HIGHLANDS,
             END_MIDLANDS, ERODED_BADLANDS, NETHER_WASTES, SMALL_END_ISLANDS, SOUL_SAND_VALLEY,
             THE_END, THE_VOID, WARPED_FOREST]
    speed: 0.125

  bad-fertile:
    biomes: [GROVE, BADLANDS, SAVANNA, BEACH, MUSHROOM_FIELDS, SNOWY_BEACH,
             SNOWY_PLAINS, SNOWY_SLOPES, SNOWY_TAIGA, STONY_PEAKS, STONY_SHORE,
             WINDSWEPT_HILLS, WOODED_BADLANDS]
    speed: 0.25

  below-average-fertile:
    biomes: [LUSH_CAVES, MANGROVE_SWAMP, OLD_growth_SPRUCE_TAIGA, SWAMP,
             TAIGA, WINDSWEPT_SAVANNA, WINDSWEPT_GRAVELLY_HILLS]
    speed: 0.35

  above-average-fertile:
    biomes: [DEEP_LUKEWARM_OCEAN, LUKEWARM_OCEAN, OCEAN]
    speed: 0.5

  fertile:
    biomes: [BAMBOO_JUNGLE, JUNGLE, FOREST, OLD_growth_BIRCH_FOREST, SPARSE_JUNGLE,
             WARM_OCEAN]
    speed: 0.75

  very-fertile:
    biomes: [RIVER, BIRCH_FOREST, CHERRY_GROVE, FLOWER_FOREST, MEADOW,
             PLAINS, SUNFLOWER_PLAINS]
    speed: 1.0

plant-types:
  plants:
    BEETROOTS:
      growth: 55
      growthDark: 25
      death: 3

    WHEAT:
      growth: 50
      growthDark: 20
      death: 4

    CARROTS:
      growth: 50
      growthDark: 25
      death: 2

    POTATO:
      growth: 40
      growthDark: 20
      death: 2

    PUMPKIN:
      growth: 50
      growthDark: 25
      death: 3

    MELON:
      growth: 50
      growthDark: 25
      death: 3

    MELON_STEM:
      growth: 50
      growthDark: 25
      death: 2

    PUMPKIN_SEEDS:
      growth: 50
      growthDark: 25
      death: 2

    MELON_SEEDS:
      growth: 50
      growthDark: 25
      death: 2

    BAMBOO:
      growth: 30
      growthDark: 15
      death: 2

    SUGAR_CANE:
      growth: 35
      growthDark: 15
      death: 2

    SPRUCE_SAPLING:
      growth: 30
      growthDark: 20
      death: 3

    ACACIA_SAPLING:
      growth: 40
      growthDark: 20
      death: 4

    BAMBOO_SAPLING:
      growth: 25
      growthDark: 12
      death: 2

    BIRCH_SAPLING:
      growth: 40
      growthDark: 20
      death: 3

    OAK_SAPLING:
      growth: 40
      growthDark: 20
      death: 3

    CHERRY_SAPLING:
      growth: 40
      growthDark: 20
      death: 5

    DARK_OAK_SAPLING:
      growth: 40
      growthDark: 35
      death: 2

    JUNGLE_SAPLING:
      growth: 40
      growthDark: 10
      death: 2

