Biomes:
  VeryBad:
    biomes: [COLD_OCEAN, DEEP_COLD_OCEAN, DESERT, DEEP_DARK, DEEP_FROZEN_OCEAN,
             FROZEN_PEAKS, FROZEN_OCEAN, FROZEN_RIVER, DRIPSTONE_CAVES, ICE_SPIKES,
             JAGGED_PEAKS, BASALT_DELTAS, CRIMSON_FOREST, END_BARRENS, END_HIGHLANDS,
             END_MIDLANDS, ERODED_BADLANDS, NETHER_WASTES, SMALL_END_ISLANDS, SOUL_SAND_VALLEY,
             THE_END, THE_VOID, WARPED_FOREST]
    speed: 0.25
  Bad:
    biomes: [GROVE, BADLANDS, SAVANNA, BEACH, MUSHROOM_FIELDS, SNOWY_BEACH,
             SNOWY_PLAINS, SNOWY_SLOPES, SNOWY_TAIGA, STONY_PEAKS, STONY_SHORE,
             WINDSWEPT_HILLS, WOODED_BADLANDS]
    speed: 0.5
  BelowTheAverage:
    biomes: [LUSH_CAVES, MANGROVE_SWAMP, OLD_GROWTH_SPRUCE_TAIGA, SWAMP,
             TAIGA, WINDSWEPT_SAVANNA, WINDSWEPT_GRAVELLY_HILLS]
    speed: 0.75
  AboveTheAverage:
    biomes: [DEEP_LUKEWARM_OCEAN, LUKEWARM_OCEAN, OCEAN]
    speed: 1.25
  Cool:
    biomes: [BAMBOO_JUNGLE, JUNGLE, FOREST, OLD_GROWTH_BIRCH_FOREST, SPARSE_JUNGLE,
             WARM_OCEAN]
    speed: 1.5
  VeryCool:
    biomes: [RIVER, BIRCH_FOREST, CHERRY_GROVE, FLOWER_FOREST, MEADOW,
             PLAINS, SUNFLOWER_PLAINS]
    speed: 2