name: RegicideAgriculture
version: '${project.version}'
main: org.regicide.regicideagriculture.RegicideAgriculture
api-version: '1.20'
description: ''
commands:
  reload:
    description: "Reload the plugin"
    permission: "regicideagriculture.command.regicideagriculture"

  types:
    description: "Show to player all of type biomes"
